openapi: 3.0.4
info:
  title: Sample API
  version: 1.0.0
  description: A sample API to demonstrate OpenAPI specification
servers:
  - url: https://api.example.com/v1
paths:
  /users:
    get:
      summary: Get a list of users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
security:                  # Global security requirements
  - bearerAuth: []
 