/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.19.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Error;
import org.springframework.lang.Nullable;
import org.openapitools.model.Student;
import org.openapitools.model.StudentCreateRequest;
import org.openapitools.model.StudentPageResponse;
import org.openapitools.model.StudentPartialUpdateRequest;
import org.openapitools.model.StudentSearchRequest;
import org.openapitools.model.StudentStatistics;
import org.openapitools.model.StudentUpdateRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-02-08T10:00:46.754234394+05:30[Asia/Kolkata]", comments = "Generator version: 7.19.0")
@Validated
@Tag(name = "Students", description = "Student management operations")
public interface StudentsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_CREATE_STUDENT = "/students";
    /**
     * POST /students : Create a new student
     * Create a new student record in the system.  Required fields: - studentNumber (unique) - name - address (complete) - cgpa - backlogs 
     *
     * @param studentCreateRequest Student object to be created (required)
     * @return Student created successfully (status code 201)
     *         or Bad request - Invalid input (status code 400)
     *         or Student with the same student number already exists (status code 409)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "createStudent",
        summary = "Create a new student",
        description = "Create a new student record in the system.  Required fields: - studentNumber (unique) - name - address (complete) - cgpa - backlogs ",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Student created successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Student.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"timestamp\":\"2024-02-06T10:30:00Z\",\"status\":400,\"error\":\"Bad Request\",\"message\":\"Validation failed\",\"path\":\"/v1/students\",\"errors\":[{\"field\":\"cgpa\",\"message\":\"must be between 0.0 and 10.0\",\"rejectedValue\":\"12.5\"},{\"field\":\"studentNumber\",\"message\":\"must match pattern ^STU[0-9]{3,6}$\",\"rejectedValue\":\"INVALID\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "409", description = "Student with the same student number already exists", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = StudentsApi.PATH_CREATE_STUDENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Student> createStudent(
        @Parameter(name = "StudentCreateRequest", description = "Student object to be created", required = true) @Valid @RequestBody StudentCreateRequest studentCreateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_DELETE_STUDENT = "/students/{studentNumber}";
    /**
     * DELETE /students/{studentNumber} : Delete student by student number
     * Permanently delete a student record from the system.  **Warning**: This operation cannot be undone. 
     *
     * @param studentNumber Unique student identifier (required)
     * @return Student deleted successfully (status code 204)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "deleteStudent",
        summary = "Delete student by student number",
        description = "Permanently delete a student record from the system.  **Warning**: This operation cannot be undone. ",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "204", description = "Student deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = StudentsApi.PATH_DELETE_STUDENT,
        produces = { "application/json" }
    )
    default ResponseEntity<Void> deleteStudent(
        @NotNull @Pattern(regexp = "^STU[0-9]{3,6}$") @Parameter(name = "studentNumber", description = "Unique student identifier", required = true, in = ParameterIn.PATH) @PathVariable("studentNumber") String studentNumber
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_ALL_STUDENTS = "/students";
    /**
     * GET /students : Get all students
     * Retrieve a paginated list of all students with optional filtering.  Query parameters allow you to: - Paginate through results - Filter by name (partial match) - Filter by minimum CGPA - Filter by city - Sort results 
     *
     * @param page Page number (0-based) (optional, default to 0)
     * @param size Number of items per page (optional, default to 20)
     * @param name Filter by student name (partial match, case-insensitive) (optional)
     * @param minCgpa Filter by minimum CGPA (optional)
     * @param city Filter by city (optional)
     * @param sortBy Field to sort by (optional, default to studentNumber)
     * @param sortOrder Sort order (optional, default to asc)
     * @return Successful response with paginated student list (status code 200)
     *         or Bad request - Invalid input (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getAllStudents",
        summary = "Get all students",
        description = "Retrieve a paginated list of all students with optional filtering.  Query parameters allow you to: - Paginate through results - Filter by name (partial match) - Filter by minimum CGPA - Filter by city - Sort results ",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Successful response with paginated student list", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StudentPageResponse.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"content\":[{\"studentNumber\":\"STU001\",\"name\":\"John Doe\",\"address\":{\"street\":\"123 Main Street\",\"city\":\"Mumbai\",\"state\":\"Maharashtra\",\"country\":\"India\"},\"cgpa\":8.5,\"backlogs\":0},{\"studentNumber\":\"STU002\",\"name\":\"Jane Smith\",\"address\":{\"street\":\"456 Park Avenue\",\"city\":\"Delhi\",\"state\":\"Delhi\",\"country\":\"India\"},\"cgpa\":9.2,\"backlogs\":1}],\"page\":{\"number\":0,\"size\":20,\"totalElements\":2,\"totalPages\":1}}"
                    )
                })

            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"timestamp\":\"2024-02-06T10:30:00Z\",\"status\":400,\"error\":\"Bad Request\",\"message\":\"Validation failed\",\"path\":\"/v1/students\",\"errors\":[{\"field\":\"cgpa\",\"message\":\"must be between 0.0 and 10.0\",\"rejectedValue\":\"12.5\"},{\"field\":\"studentNumber\",\"message\":\"must match pattern ^STU[0-9]{3,6}$\",\"rejectedValue\":\"INVALID\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = StudentsApi.PATH_GET_ALL_STUDENTS,
        produces = { "application/json" }
    )
    default ResponseEntity<StudentPageResponse> getAllStudents(
        @Min(value = 0) @Parameter(name = "page", description = "Page number (0-based)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "page", required = false, defaultValue = "0") Integer page,
        @Min(value = 1) @Max(value = 100) @Parameter(name = "size", description = "Number of items per page", in = ParameterIn.QUERY) @Valid @RequestParam(value = "size", required = false, defaultValue = "20") Integer size,
        @Parameter(name = "name", description = "Filter by student name (partial match, case-insensitive)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) @Nullable String name,
        @DecimalMin(value = "0.0") @DecimalMax(value = "10.0") @Parameter(name = "minCgpa", description = "Filter by minimum CGPA", in = ParameterIn.QUERY) @Valid @RequestParam(value = "minCgpa", required = false) @Nullable Double minCgpa,
        @Parameter(name = "city", description = "Filter by city", in = ParameterIn.QUERY) @Valid @RequestParam(value = "city", required = false) @Nullable String city,
        @Parameter(name = "sortBy", description = "Field to sort by", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sortBy", required = false, defaultValue = "studentNumber") String sortBy,
        @Parameter(name = "sortOrder", description = "Sort order", in = ParameterIn.QUERY) @Valid @RequestParam(value = "sortOrder", required = false, defaultValue = "asc") String sortOrder
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"page\" : { \"number\" : 0, \"size\" : 20, \"totalPages\" : 8, \"totalElements\" : 150 }, \"content\" : [ { \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 }, { \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 } ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_STUDENT_BY_NUMBER = "/students/{studentNumber}";
    /**
     * GET /students/{studentNumber} : Get student by student number
     * Retrieve a single student record by their unique student number
     *
     * @param studentNumber Unique student identifier (required)
     * @return Student found (status code 200)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "getStudentByNumber",
        summary = "Get student by student number",
        description = "Retrieve a single student record by their unique student number",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Student found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Student.class))
            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = StudentsApi.PATH_GET_STUDENT_BY_NUMBER,
        produces = { "application/json" }
    )
    default ResponseEntity<Student> getStudentByNumber(
        @NotNull @Pattern(regexp = "^STU[0-9]{3,6}$") @Parameter(name = "studentNumber", description = "Unique student identifier", required = true, in = ParameterIn.PATH) @PathVariable("studentNumber") String studentNumber
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_GET_STUDENT_STATISTICS = "/students/statistics";
    /**
     * GET /students/statistics : Get student statistics
     * Retrieve statistical information about all students
     *
     * @return Statistics retrieved successfully (status code 200)
     */
    @Operation(
        operationId = "getStudentStatistics",
        summary = "Get student statistics",
        description = "Retrieve statistical information about all students",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Statistics retrieved successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = StudentStatistics.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = StudentsApi.PATH_GET_STUDENT_STATISTICS,
        produces = { "application/json" }
    )
    default ResponseEntity<StudentStatistics> getStudentStatistics(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"averageCgpa\" : 7.85, \"topPerformers\" : 15, \"cityDistribution\" : { \"Mumbai\" : 45, \"Delhi\" : 35 }, \"studentsWithNoBacklogs\" : 120, \"totalStudents\" : 150, \"studentsWithBacklogs\" : 30 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_PARTIAL_UPDATE_STUDENT = "/students/{studentNumber}";
    /**
     * PATCH /students/{studentNumber} : Partially update student
     * Update specific fields of a student record.  Only the fields provided in the request body will be updated. Other fields will remain unchanged. 
     *
     * @param studentNumber Unique student identifier (required)
     * @param studentPartialUpdateRequest Fields to update (required)
     * @return Student updated successfully (status code 200)
     *         or Bad request - Invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "partialUpdateStudent",
        summary = "Partially update student",
        description = "Update specific fields of a student record.  Only the fields provided in the request body will be updated. Other fields will remain unchanged. ",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Student updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Student.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"timestamp\":\"2024-02-06T10:30:00Z\",\"status\":400,\"error\":\"Bad Request\",\"message\":\"Validation failed\",\"path\":\"/v1/students\",\"errors\":[{\"field\":\"cgpa\",\"message\":\"must be between 0.0 and 10.0\",\"rejectedValue\":\"12.5\"},{\"field\":\"studentNumber\",\"message\":\"must match pattern ^STU[0-9]{3,6}$\",\"rejectedValue\":\"INVALID\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = StudentsApi.PATH_PARTIAL_UPDATE_STUDENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Student> partialUpdateStudent(
        @NotNull @Pattern(regexp = "^STU[0-9]{3,6}$") @Parameter(name = "studentNumber", description = "Unique student identifier", required = true, in = ParameterIn.PATH) @PathVariable("studentNumber") String studentNumber,
        @Parameter(name = "StudentPartialUpdateRequest", description = "Fields to update", required = true) @Valid @RequestBody StudentPartialUpdateRequest studentPartialUpdateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_SEARCH_STUDENTS = "/students/search";
    /**
     * POST /students/search : Advanced student search
     * Perform advanced search with multiple criteria.  Supports complex queries with multiple filters combined. 
     *
     * @param studentSearchRequest Search criteria (required)
     * @return Search results (status code 200)
     *         or Bad request - Invalid input (status code 400)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "searchStudents",
        summary = "Advanced student search",
        description = "Perform advanced search with multiple criteria.  Supports complex queries with multiple filters combined. ",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Search results", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Student.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"timestamp\":\"2024-02-06T10:30:00Z\",\"status\":400,\"error\":\"Bad Request\",\"message\":\"Validation failed\",\"path\":\"/v1/students\",\"errors\":[{\"field\":\"cgpa\",\"message\":\"must be between 0.0 and 10.0\",\"rejectedValue\":\"12.5\"},{\"field\":\"studentNumber\",\"message\":\"must match pattern ^STU[0-9]{3,6}$\",\"rejectedValue\":\"INVALID\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = StudentsApi.PATH_SEARCH_STUDENTS,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<List<Student>> searchStudents(
        @Parameter(name = "StudentSearchRequest", description = "Search criteria", required = true) @Valid @RequestBody StudentSearchRequest studentSearchRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 }, { \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_UPDATE_STUDENT = "/students/{studentNumber}";
    /**
     * PUT /students/{studentNumber} : Update student by student number
     * Update an existing student record.  All fields in the request body will replace existing values. Student number cannot be changed. 
     *
     * @param studentNumber Unique student identifier (required)
     * @param studentUpdateRequest Updated student object (required)
     * @return Student updated successfully (status code 200)
     *         or Bad request - Invalid input (status code 400)
     *         or Resource not found (status code 404)
     *         or Internal server error (status code 500)
     */
    @Operation(
        operationId = "updateStudent",
        summary = "Update student by student number",
        description = "Update an existing student record.  All fields in the request body will replace existing values. Student number cannot be changed. ",
        tags = { "Students" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Student updated successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Student.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad request - Invalid input", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"timestamp\":\"2024-02-06T10:30:00Z\",\"status\":400,\"error\":\"Bad Request\",\"message\":\"Validation failed\",\"path\":\"/v1/students\",\"errors\":[{\"field\":\"cgpa\",\"message\":\"must be between 0.0 and 10.0\",\"rejectedValue\":\"12.5\"},{\"field\":\"studentNumber\",\"message\":\"must match pattern ^STU[0-9]{3,6}$\",\"rejectedValue\":\"INVALID\"}]}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Resource not found", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal server error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        },
        security = {
            @SecurityRequirement(name = "bearerAuth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = StudentsApi.PATH_UPDATE_STUDENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Student> updateStudent(
        @NotNull @Pattern(regexp = "^STU[0-9]{3,6}$") @Parameter(name = "studentNumber", description = "Unique student identifier", required = true, in = ParameterIn.PATH) @PathVariable("studentNumber") String studentNumber,
        @Parameter(name = "StudentUpdateRequest", description = "Updated student object", required = true) @Valid @RequestBody StudentUpdateRequest studentUpdateRequest
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"address\" : { \"country\" : \"India\", \"city\" : \"Mumbai\", \"street\" : \"123 Main Street\", \"state\" : \"Maharashtra\" }, \"backlogs\" : 0, \"createdDate\" : \"2024-01-15T09:00:00Z\", \"lastModifiedDate\" : \"2024-02-06T10:30:00Z\", \"studentNumber\" : \"STU001\", \"name\" : \"John Doe\", \"cgpa\" : 8.5 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"path\" : \"/v1/students\", \"error\" : \"Bad Request\", \"message\" : \"Validation failed for field 'cgpa'\", \"errors\" : [ { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" }, { \"field\" : \"cgpa\", \"message\" : \"must be between 0.0 and 10.0\", \"rejectedValue\" : \"12.5\" } ], \"timestamp\" : \"2024-02-06T10:30:00Z\", \"status\" : 400 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
